### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by Zakor11** [KompBasierte1718/Client#1]
Travis CI kann bisher noch nicht korrekt builden. Fehler finden und beheben.

**Comment by Zakor11** [comment]
Neue Fehlermeldung nach Commit 213e19d697f6ed18b5c8c3f8c586bf6bbd635ecf : 

```
The command "eval ./gradlew assemble " failed. Retrying, 3 of 3.

/home/travis/.travis/job_stages: line 236: ./gradlew: Permission denied

The command "eval ./gradlew assemble " failed 3 times.

The command "./gradlew assemble" failed and exited with 126 during .
```

Scheinbar ein Permission-Fehler. 

- [x] Sudo-Notwendigkeit prüfen
- [x] evtl. Travis.yml überprüfen und anpassen

**Comment by smartmaracl** [comment]
Bekomme nur:

> Sorry, we experienced an error.
> 
> request_id=3f0a8561-c63a-47ff-b3b4-41ec06e07231

Kann da leider auch nichts machen. Habe es mir zwar angeschaut aber die Oberfläche ist nicht sehr übersichtlich

**Comment by Zakor11** [comment]
Fixed mit commit 13c985cc386b16d9fa76ff9530c4e35380717b84 . Travis läuft nun problemlos
